name: Molecule Testes on Push

on:  
  push:
  pull_request:
    branches:
      - main
      - non_prod
      - redhatmigration
     
jobs:
  find_changed_roles:
    runs-on: self-hosted
    outputs:
      get_roles: ${{ steps.get_changed_paths.outputs.ansible_roles }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2
          ref: 'main'
          ##testadded test test test test deepu

      - name: Get Changed Files
        id: get_changed
        run: echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r HEAD | xargs)"

      - name: Get Changed Roles
        id: get_changed_roles
        run: echo "::set-output name=roles::$(for i in ${{ steps.get_changed.outputs.files }} ; do echo $i | grep 'roles/' | awk -F '/' '{print $1 "/" $2 "/"}'; done | sort | uniq | xargs )"

      - name: Format, so GitHub Actions can list over an output list
        id: get_changed_paths
        run: |
          content="[$(for l in ${{ steps.get_changed_roles.outputs.roles }} ; do echo \"$l\",; done )]"
          echo "::set-output name=ansible_roles::$content"

  molecule_tests:
    runs-on: self-hosted 
    needs: find_changed_roles
    # Skip there is no change in any roles. Example change in a README.md
    if: ${{ needs.find_changed_roles.outputs.get_roles != '[]' }}
    strategy:
      matrix:
        value: ${{ fromJSON(needs.find_changed_roles.outputs.get_roles) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Install Python 3.9
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "pypy3.9"

      # - name: Install Ansible Python packages
      #   run: pip3 install ansible molecule ansible-lint docker molecule[docker]
     
      # - name: Change Dir 
      #   run: cd /home/ansible/actions-runner/_work/ansible_roles_testing/ansible_roles_testing/
 
      # - name: Changing virtuval Env
      #   run: source /home/ansible/ansible_molecule/bin/activate
      
      # - name: pwd
      #   run: pwd
      
      # - name: check podman version 
      #   run: podman --version
      # # - name: ansible lint
      # #   run: ansible-lint
      
      # - name: check podman molecule verison  
      #   run: molecule --version
      
      - name: pwd
        run: pwd

      - name: Run molecule script file
        run: | 
           chmod a+x molecule.sh
           ./molecule.sh
        # env:
        #   PY_COLORS: "1"
        #   ANSIBLE_FORCE_COLOR: "1"
        # working-directory: '/home/ansible/actions-runner/_work/ansible_roles_testing/ansible_roles_testing/collections/ansible_collections/infra/lab/roles/httpd/'
        # working-directory: ${{ matrix.value }}
